/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_drill_madlib_jni_DrillJni */

#ifndef _Included_org_apache_drill_madlib_jni_DrillJni
#define _Included_org_apache_drill_madlib_jni_DrillJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    array_dot
 * Signature: ([[D[[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_drill_madlib_jni_DrillJni_array_1dot
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    array_scalar_mult
 * Signature: ([DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_array_1scalar_1mult
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    linregr_transition
 * Signature: ([BD[D)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_linregr_1transition
  (JNIEnv *, jobject, jbyteArray, jdouble, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    linrger_final
 * Signature: ([B)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_drill_madlib_jni_DrillJni_linrger_1final
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    hetero_linregr_transition
 * Signature: ([BD[D[D)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_hetero_1linregr_1transition
  (JNIEnv *, jobject, jbyteArray, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    hetero_linregr_final
 * Signature: ([B)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_drill_madlib_jni_DrillJni_hetero_1linregr_1final
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    linregr_merge_states
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_linregr_1merge_1states
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    hetero_linregr_merge_states
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_hetero_1linregr_1merge_1states
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_cg_step_transition
 * Signature: ([DZ[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1cg_1step_1transition
  (JNIEnv *, jobject, jdoubleArray, jboolean, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_cg_step_merge_states
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1cg_1step_1merge_1states
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_cg_step_final
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1cg_1step_1final
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_cg_step_distance
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1cg_1step_1distance
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_cg_result
 * Signature: ([D)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1cg_1result
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_irls_step_transition
 * Signature: ([DZ[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1irls_1step_1transition
  (JNIEnv *, jobject, jdoubleArray, jboolean, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_irls_step_merge_states
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1irls_1step_1merge_1states
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_irls_step_final
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1irls_1step_1final
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_irls_step_distance
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1irls_1step_1distance
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_irls_result
 * Signature: ([D)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1irls_1result
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_igd_step_transition
 * Signature: ([DZ[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1igd_1step_1transition
  (JNIEnv *, jobject, jdoubleArray, jboolean, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_igd_step_merge_states
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1igd_1step_1merge_1states
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_igd_step_final
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1igd_1step_1final
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_igd_step_distance
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1igd_1step_1distance
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_igd_result
 * Signature: ([D)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1igd_1result
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_predict
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1predict
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    logregr_predict_prob
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_drill_madlib_jni_DrillJni_logregr_1predict_1prob
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    correlation_transition
 * Signature: ([[D[D[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_correlation_1transition
  (JNIEnv *, jobject, jobjectArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    correlation_merge
 * Signature: ([[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_correlation_1merge
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     org_apache_drill_madlib_jni_DrillJni
 * Method:    correlation_final
 * Signature: ([[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_drill_madlib_jni_DrillJni_correlation_1final
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
